/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class piaccess_PiDb */

#ifndef _Included_piaccess_PiDb
#define _Included_piaccess_PiDb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     piaccess_PiDb
 * Method:    FindPointNumber
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_piaccess_PiDb_FindPointNumber
  (JNIEnv *, jobject, jstring);

/*
 * Class:     piaccess_PiDb
 * Method:    GetSingleSNData
 * Signature: (Lpiaccess/Tag;)I
 */
JNIEXPORT jint JNICALL Java_piaccess_PiDb_GetSingleSNData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     piaccess_PiDb
 * Method:    GetArraySNData
 * Signature: ([Lpiaccess/Tag;)I
 */
JNIEXPORT jint JNICALL Java_piaccess_PiDb_GetArraySNData
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     piaccess_PiDb
 * Method:    DateTest
 * Signature: (Ljava/util/Calendar;Ljava/util/Calendar;)V
 */
JNIEXPORT void JNICALL Java_piaccess_PiDb_DateTest
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     piaccess_PiDb
 * Method:    EnumTest
 * Signature: ()Lpiaccess/PIvaluetype;
 */
JNIEXPORT jobject JNICALL Java_piaccess_PiDb_EnumTest
  (JNIEnv *, jobject);

/*
 * Class:     piaccess_PiDb
 * Method:    GetARCount
 * Signature: (Ljava/util/Calendar;Ljava/util/Calendar;I)I
 */
JNIEXPORT jint JNICALL Java_piaccess_PiDb_GetARCount
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     piaccess_PiDb
 * Method:    GetARData
 * Signature: (Ljava/util/Calendar;Ljava/util/Calendar;I[Lpiaccess/Tag;)I
 */
JNIEXPORT jint JNICALL Java_piaccess_PiDb_GetARData
  (JNIEnv *, jobject, jobject, jobject, jint, jobjectArray);

/*
 * Class:     piaccess_PiDb
 * Method:    GetArrayARData
 * Signature: ([Ljava/util/Calendar;I[Lpiaccess/Tag;)I
 */
JNIEXPORT jint JNICALL Java_piaccess_PiDb_GetArrayARData
  (JNIEnv *, jobject, jobjectArray, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
